---
- name: Configure switch with hostname S2
  hosts: S2
  become: true

  tasks:

    - name: Create STUD1(VLAN10)
      cisco.ios.ios_config:
        lines:
          - name STUD1
        parents: vlan 10

    - name: Create STUD2(VLAN20)
      cisco.ios.ios_config:
        lines:
          - name STUD2
        parents: vlan 20

    - name: Create VLAN99
      cisco.ios.ios_config:
        lines:
          - name VLAN99
        parents: vlan 99

    - name: Turn on MGMT port GigabitEthernet1/0/1
      cisco.ios.ios_config:
        lines:
          - no shutdown
        parents: int g1/0/1

    - name: Turn on MGMT port GigabitEthernet1/0/2
      cisco.ios.ios_config:
        lines:
          - no shutdown
        parents: int g1/0/2

    - name: Configure port-channel 1
      cisco.ios.ios_config:
        lines:
          - switchport mode trunk
          - switchport trunk allowed vlan 10,20,99
        parents: int port-channel 1

    - name: Enable port-channel 1 on interface range
      cisco.ios.ios_config:
        lines:
          - switchport mode trunk
          - switchport trunk allowed vlan 10,20,99
          - channel-group 1 mode active
        parents: int range g1/0/23-24
