---
- name: Configure switch with hostname S1
  hosts: S1
  become: yes

  tasks:

    - name: Create VLAN10
      cisco.ios.ios_config:
        lines:
          - name VLAN10
        parents: vlan 10

    - name: Create VLAN20
      cisco.ios.ios_config:
        lines:
          - name VLAN20
        parents: vlan 20

    - name: Create VLAN99
      cisco.ios.ios_config:
        lines:
          - name VLAN99
        parents: vlan 99

    - name: Configure MGMT interface GigabitEthernet1/0/1 as trunk
      cisco.ios.ios_config:
        lines:
          - switchport mode trunk
          - switchport trunk allowed vlan 10,20,99
        parents: int g1/0/1

    - name: Configure MGMT interface GigabitEthernet1/0/1 as trunk
      cisco.ios.ios_config:
        lines:
          - switchport mode trunk
          - switchport trunk allowed vlan 10,20,99
        parents: int g1/0/2

    - name: Configure port-channel 1
      cisco.ios.ios_config:
        lines:
          - switchport mode trunk
          - switchport trunk allowed vlan 10,20,99
        parents: int port-channel 1

    - name: Enable port-channel 1 on interface range
      cisco.ios.ios_config:
        lines:
          - switchport mode trunk
          - switchport trunk allowed vlan 10,20,99
          - channel-group 1 mode active
        parents: int range g1/0/23-24