---
- name: Configure switch with hostname S1
  hosts: S1
  become: true

  tasks:

    - name: Configure STUD1(VLAN10)
      cisco.ios.ios_vlans:
        config:
          - name: STUD1
            vlan_id: 10
            state: active

    - name: Configure STUD2(VLAN20)
      cisco.ios.ios_vlans:
        config:
          - name: STUD2
            vlan_id: 20
            state: active

    - name: Configure VLAN 99
      cisco.ios.ios_vlans:
        config:
          - name: vlan_99
            vlan_id: 99
            state: active

    - name: Turn on MGMT port GigabitEthernet1/0/1
      cisco.ios.ios_config:
        lines:
          - no shutdown
        parents: int g1/0/1

    - name: Turn on MGMT port GigabitEthernet1/0/2
      cisco.ios.ios_config:
        lines:
          - no shutdown
        parents: int g1/0/2

    - name: Configure interface GigabitEthernet1/0/1 as trunk
      cisco.ios.ios_config:
        lines:
          - switchport mode trunk
          - switchport trunk allowed vlan 10,20,99
        parents: int g1/0/1

    - name: Configure interface GigabitEthernet1/0/2 as trunk
      cisco.ios.ios_config:
        lines:
          - switchport mode trunk
          - switchport trunk allowed vlan 10,20,99
        parents: int g1/0/2

    - name: Configure port-channel 1
      cisco.ios.ios_config:
        lines:
          - switchport mode trunk
          - switchport trunk allowed vlan 10,20,99
        parents: int port-channel 1

    - name: Enable port-channel 1 on interface range
      cisco.ios.ios_config:
        lines:
          - switchport mode trunk
          - switchport trunk allowed vlan 10,20,99
          - channel-group 1 mode active
        parents: int range g1/0/23-24
